
package no.hib.mod250.anthrax.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnthraxWebServices", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnthraxWebServices {


    /**
     * 
     * @return
     *     returns java.util.List<no.hib.mod250.anthrax.service.ProductView>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveAuctions", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.GetActiveAuctions")
    @ResponseWrapper(localName = "getActiveAuctionsResponse", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.GetActiveAuctionsResponse")
    @Action(input = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/getActiveAuctionsRequest", output = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/getActiveAuctionsResponse")
    public List<ProductView> getActiveAuctions();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.SayHelloWorldFromResponse")
    @Action(input = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/sayHelloWorldFromRequest", output = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns no.hib.mod250.anthrax.service.SoapMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bidForAuction", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.BidForAuction")
    @ResponseWrapper(localName = "bidForAuctionResponse", targetNamespace = "http://soap.services.anthrax.mod250.hib.no/", className = "no.hib.mod250.anthrax.service.BidForAuctionResponse")
    @Action(input = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/bidForAuctionRequest", output = "http://soap.services.anthrax.mod250.hib.no/AnthraxWebServices/bidForAuctionResponse")
    public SoapMessage bidForAuction(
        @WebParam(name = "arg0", targetNamespace = "")
        NewBidView arg0);

}
